#!/usr/bin/env bash
set -euo pipefail

cp tags/prod.versions .env.runtime # Bring docker TAGs

cat <<EOF >> .env.runtime

PORT_PARKING_LOT_FRONTEND=${PORT_PARKING_LOT_FRONTEND}
PORT_PARKING_LOT_BACKEND=${PORT_PARKING_LOT_BACKEND}

POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql/${POSTGRES_DB}
SECRET_KEY=${SECRET_KEY}
AES_KEY=${AES_KEY}
HMAC_KEY=${HMAC_KEY}
ENABLE_SIGNUP=true

PARKING_LOT_FRONTEND_URL=${PARKING_LOT_FRONTEND_URL}
PARKING_LOT_BACKEND_URL=${PARKING_LOT_BACKEND_URL}

EOF

echo ".env.runtime created"